<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 *
 * @package   block_mbsschooltitle
 * @copyright Andreas Wagner, ISB Bayern
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/** transfer old header data (formerly generated by block_custom_category)
 * 
 * @global record $CFG
 * @global database $DB
 * @return boolean true if succeeded
 */
function xmldb_block_mbsschooltitle_install() {
    global $CFG, $DB;

    if (file_exists($CFG->dirroot.'/blocks/custom_category/version.php')) {
        
        // If title data for school categories is empty, try to fetch it from
        // block_custom_category, but only for the school categories (i. e. depth = 3).
        if (!$exists = $DB->get_records('block_mbsschooltitle')) {
            // is empty
            
            $sql = "SELECT c.* FROM {block_custom_category} c 
                    JOIN {course_categories} cat ON c.categoryid = cat.id
                    WHERE cat.depth = '3'";
            
            if ($data = $DB->get_records_sql($sql)) {
                
                foreach ($data as $date) {
                    $date->image = $date->background_image;
                    $DB->insert_record('block_mbsschooltitle', $date);
                }
            }
        }
    }
   
    return true;
}