- theme/mebis/vendor/bootstrap/bootstrap.min.js
- theme/mebis/vendor/jcarousel/jcarousel.min.js
- theme/mebis/vendor/velocity.min.js
- theme/mebis/vendor/tooltipster/jquery.tooltipster.min.js
- theme/mebis/vendor/stackblur.js
- theme/mebis/vendor/jquery.shuffle.js

# Customs
- theme/mebis/vendor/jquery.equalizer.js